spring:
  application:
    name: Credential-Vaultspring

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/credential-vault
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

app:
  token:
    secret-key: ${JWT_SECRET_KEY:Y29mcmUtZGUtc2VuaGFzLWFwaS1kZXBsb3k=}

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always